services:
  - type: web
    name: my-js-server
    env: node
    repo: https://github.com/ticia1911/Webserver
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
